### ISSUE TITLE
Start engines on different cores

### ISSUE THREAD

**Issue by mcostalba** [hazzl/pyshbench#3]
Please see this one:

https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/nk0rr-wVq-k

**Comment by hazzl** [comment]
Hm, I would prefer a solution that is not Linux-only. Especially as I have the impreesion that a significant amount of the stockfish crowd is on Windows. But I guess I'll take Roland's approach as an immediate stop gap that can later be improved upon.

**Comment by hazzl** [comment]
Fixed in d728f1a2538c6972891eebf3b73cc97bbc449154
