### ISSUE TITLE
Change output of usage instruction

### ISSUE THREAD

**Issue by joergoster** [hazzl/pyshbench#4]
It's a bit misleading if the readme provides the correct syntax, while the output in case of wrong usage tells something different. ;-)
Changed code:

```
if (len(sys.argv) != 4 or int(sys.argv[3]) < 2):
	exit("Usage:\n" + sys.argv[0] + " base test #runs\nwhere #runs >= 2")
```

**Comment by hazzl** [comment]
fixed in 28f17e9708ce93d873ee1c52f44be068289b15bc
